baseURL = "http://www.matheuscastiglioni.com.br/"
defaultContentLanguage = "pt-br"
languageCode = "pt-br"
theme = "matheuscastiglioni"
title = "Matheus Castiglioni"

[params]
    author = "Matheus Castiglioni"
    authorWork = "Desenvolvedor Full Stack"
    photoPerfil = "http://blog.matheuscastiglioni.com.br/arquivo/download/usuarios/matheus-castiglioni.jpg"
